# This file was generated by GoReleaser. DO NOT EDIT.
class Gvm < Formula
  desc "GVM will allow you to easily install, use and/or delete Golang versions from the official servers."
  homepage ""
  url "https://github.com/tfournier/gvm/releases/download/0.0.11/gvm_Darwin_x86_64.tar.gz"
  version "0.0.11"
  sha256 "2b81db336ea65ec5bfe11c744eea91b7b7d6da582d81652f8b742fd998bd8176"

  def install
    bin.install "gvm"
  end
end
