# This file was generated by GoReleaser. DO NOT EDIT.
class Gvm < Formula
  desc "GVM will allow you to easily install, use and/or delete Golang versions from the official servers."
  homepage ""
  url "https://github.com/tfournier/gvm/releases/download/1.1.0/gvm_Darwin_x86_64.tar.gz"
  version "1.1.0"
  sha256 "020866e736101027b12339b13a5382e3de1e74569cc1f6b9fda72c7553c2c3da"

  def install
    bin.install "gvm"
  end
end
